# Some useful notes can be found at https://conda-forge.hackpad.com/BLAS-Numpy-Friends-86De62hoNdT

# The version should be in the form X.Y, where X denotes major infrastructural change to how blas is managed,
# and Y denoting blas priority. Currently Y=0 not default, Y=1 default blas.
{% set Y = 1 if blas == 'openblas' else 0 %}
package:
  name: blas
  version: 2.{{ Y }}

build:
  # We mustn't use the build number in the blas package - because we are defining the string,
  # manually we would not be producing unique filenames.
  number: 0
  string: {{ blas }}

requirements: {}

test:
  commands:
    - echo "I'm a metapackage"

about:
  home: https://github.com/conda-forge/blas-feedstock
  license: BSD 3-clause
  summary: Metapackage to select the BLAS variant. Use conda's pinning mechanism in your environment to control which variant you want.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
