# Some useful notes can be found at https://conda-forge.hackpad.com/BLAS-Numpy-Friends-86De62hoNdT

{% set variant = os.environ.get('BLAS_VARIANT', 'openblas') %}

# The version should be in the form X.Y, where X denotes major infrastructural change to how blas is managed,
# and Y denoting blas priority. Currently Y=0 not default, Y=1 default blas.
{% set Y = 1 if variant == 'openblas' else 0 %}
package:
  name: blas
  version: 1.{{ Y }}

build:
  # We mustn't use the build number in the blas package - because we are defining the string,
  # manually we would not be producing unique filenames.
  number: 1
  string: {{ variant }}
  track_features:
    # The "blas" package must always track a feature, else it will be
    # prioritised over all others.
    - blas_{{ variant }}

{% if variant != "noblas" %}
requirements:
  run:
    - {{ variant }}
{% endif %}

test: {}

about:
  home: https://github.com/conda-forge/blas-feedstock
  license: BSD 3-clause
  summary: Metapackage to select the BLAS variant. Use conda's pinning mechanism in your environment to control which variant you want.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
