matrix:
  - [[BLAS_VARIANT, 'openblas']]
  - [[BLAS_VARIANT, 'noblas']]
  - [[BLAS_VARIANT, 'mkl']]
  - [[BLAS_VARIANT, 'lapack']]
  - [[BLAS_VARIANT, 'clapack']]
travis:
  secure:
    BINSTAR_TOKEN: VVBp7a3BLCMnyAv8rRxkrWq5FSpC77q9DdBR49ix7LJMUzwzb5jLy+/Pi5Iw1tHdWdVquUQsURHlrJbjp85/2qtMDg4torB/JATjlGeZwrxFxwdNmj2qAZgF6UJv7p5joaORDPO3x1Y5Wj2WujkIKzFEhgLpzoX/t615qg5xoILy7JYTSBXHYcFqR3P173ZARh4Vx48sgNfb+RQoXD8MMXRssrxOv7FKUJAA3IgUx1UvyyQ+JmH2Fieb4VV2x0N2nSb7eyvFhLnE62SX6soTC+JKZJO5r3QAzbY0P6lCzgN29BSCI+AjgA/tDpF5Smxj7WYhU6leQHrsGRl+OktkZ2FIcUF7GlxlbrcEACJ1Fo++SQIxmwvFM6ju4JEFJBKsz5fd5iucWVZw/1ZH9pijdxieISVTJwJHfA2WRF6P/jdecsNWR0v0IPC1XDgTHUItXg22Bx7UiHcg8/9mbM87u6aBad7pJegziC7AWRG99S9WeN6ELpMVgbb7w7+wvcjbyis2Hv2bxdAOaTP4x77TBncn7cpcterPwvjcBoemGXTLjxByJavBIJElX/gK4VeNW58I92LXaD8131nH6M3CTZaRJe2/9QfI5C0KPqNf/EJl7EvPYolV4sIzBiZRUX7xoTzAIltnhELSG+jEB1kpEPdtu3K6qyeqeajOzeQssp4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
